# Generated by Django 4.2.7 on 2024-02-03 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_post_likes_like_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like_post",
            old_name="post_id",
            new_name="post",
        ),
    ]
