# Generated by Django 4.2.7 on 2024-02-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_rename_post_id_like_post_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to="blog.profile"
            ),
        ),
    ]
