# Generated by Django 4.2.7 on 2024-02-10 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_remove_post_likes_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
