# Generated by Django 4.2.7 on 2024-03-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_profile_followers_followrelationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
    ]
